"""""""""""""""""""""""""""""
" Mitch Vollebregt .vimrc profile
" Sept 29, 2015
"""""""""""""""""""""""""""""

" Dependencies
" vim-plug https://github.com/junegunn/vim-plug
" fzf https://github.com/junegunn/fzf
" ag https://github.com/ggreer/the_silver_searcher
" sourcecode pro font
"

""""""""""""""""""""""""""
" Plug settings
""""""""""""""""""""""""""
set nocompatible

call plug#begin('~/.vim/plugged')

Plug 'edkolev/tmuxline.vim'
Plug 'vim-airline/vim-airline'
Plug 'mattn/emmet-vim'
Plug 'scrooloose/nerdTree'
Plug 'dracula/vim', { 'as': 'dracula' }
Plug 'terryma/vim-multiple-cursors'
Plug 'jiangmiao/auto-pairs'
Plug 'plasticboy/vim-markdown'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-rhubarb'
"Plug 'vim-ruby/vim-ruby'
Plug 'mileszs/ack.vim'
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-rails'
Plug 'romainl/vim-qf'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'ibhagwan/fzf-lua'
Plug 'jparise/vim-graphql'

Plug 'neovim/nvim-lspconfig'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-path'
Plug 'hrsh7th/cmp-cmdline'
Plug 'hrsh7th/nvim-cmp'

" For vsnip users.
Plug 'hrsh7th/cmp-vsnip'
Plug 'hrsh7th/vim-vsnip'

Plug 'janko/vim-test'
Plug 'ojroques/nvim-lspfuzzy'
Plug 'tpope/vim-dispatch'

Plug 'Shopify/shadowenv.vim'


call plug#end()


""""""""""""""""""""""""""
" Custom settings
""""""""""""""""""""""""""
" fzf searching settings
nmap <C-p> :Files<CR>

nmap <C-o> :Buffers<CR>

nmap <C-_> :Rg <CR>
nmap <silent> <C-f> :Rg <C-R><C-W><CR>

nmap <C-h> :History

let g:fzf_layout = { 'down': '~20%' }
let g:fzf_preview_window = 'right:40%'


" close buffer with \q
nmap <leader>q :bp<cr>:bd #<cr>

" toggle git gutter with \g
nmap <leader>g :GitGutterToggle<cr>

" toggle spelling use \s
imap <Leader>s <C-o>:setlocal spell! spelllang=en_us<CR>
nmap <Leader>s :setlocal spell! spelllang=en_us<CR>

" start relative numbering
function! NumberToggle()
  if(&relativenumber == 1)
    set nornu
  else
    set relativenumber
  endif
endfunc

nnoremap <leader>r :call NumberToggle()<cr>
nnoremap <C-b> :call NumberToggle()<cr>
:au FocusLost * :set nornu
:au FocusGained * :set relativenumber
" end relative numbering

" nerdtree settings
""""""""""""""""""""""""""
map <C-t> :NERDTreeFind<CR>

" General settings
"""""""""""""""""""""""""""
color dracula
syntax on  "Enables syntax highlighting for programming languages

let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#fnamemod = ':t' "only show filename in buffer
set laststatus=2
let g:tmuxline_powerline_separators = 0
let g:airline_powerline_fonts = 1

" Tab and shift tab cycle through buffers
nmap  <silent>   <tab>  :if &modifiable && !&readonly && &modified <CR> :write<CR> :endif<CR>:bnext<CR>
nmap  <silent> <s-tab>  :if &modifiable && !&readonly && &modified <CR> :write<CR> :endif<CR>:bprevious<CR>

set noswapfile
set t_Co=256
set t_ut= "Fix issue with background of lines being different colour than screen background
set clipboard=unnamed
set mouse=a
set showmatch
set autoindent
set cindent  "Automatically indents lines after opening a bracket
set number
set smarttab
set shiftwidth=2
set expandtab
set backspace=2
set tabstop=2
set listchars=tab:»\ ,extends:›,precedes:‹,nbsp:·,trail:· "list bad spaces
set hidden "Maintain buffer data to allow undo after switching buffers
set smartcase "Search case sensitive and fallback on insensitive"
set hlsearch "Highlight while searching
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/

" Fade out sorbet signatures
augroup format_ruby
  autocmd Syntax ruby syn region sorbetSig start='sig {' end='}'
  autocmd Syntax ruby syn region sorbetSig start='sig do' end='end'
  autocmd Syntax ruby hi def link sorbetSig Comment
augroup END

" Vim Test
nmap <silent> <leader>tn :TestNearest<CR>
nmap <silent> <leader>tf :TestFile<CR>
nmap <silent> <leader>ts :TestSuite<CR>
nmap <silent> <leader>tl :TestLast<CR>
nmap <silent> <leader>tg :TestVisit<CR>
let test#strategy = "dispatch"
let dispatch_tmux_pipe_pane = 1

" Fzf
" An action can be a reference to a function that processes selected lines
function! s:build_quickfix_list(lines)
  call setqflist(map(copy(a:lines), '{ "filename": v:val }'))
  copen
  cc
endfunction

let g:fzf_action = {
  \ 'ctrl-q': function('s:build_quickfix_list'),
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-x': 'split',
  \ 'ctrl-v': 'vsplit' }


lua << EOF

--
-- CMP
--

local cmp = require 'cmp'

cmp.setup({
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },
  mapping = cmp.mapping.preset.insert({
    ['<C-b>'] = cmp.mapping.scroll_docs(-4),
    ['<C-f>'] = cmp.mapping.scroll_docs(4),
    ['<C-Space>'] = cmp.mapping.complete(),
    ['<C-e>'] = cmp.mapping.abort(),
    ['<Tab>'] = cmp.mapping(cmp.mapping.select_next_item(), { 'i', 's' }),
    ['<S-Tab>'] = cmp.mapping(cmp.mapping.select_prev_item(), { 'i', 's' }),
    ['<CR>'] = cmp.mapping.confirm({ select = false }),
  }),
  sources = cmp.config.sources({
    { name = 'nvim_lsp' },
    { name = 'vsnip' }, -- For vsnip users.
  }, {
    { name = 'buffer' },
  })
})

-- Use cmdline & path source for ':' (if you enabled `native_menu`, this won't work anymore).
cmp.setup.cmdline(':', {
  mapping = cmp.mapping.preset.cmdline(),
  sources = cmp.config.sources({
    { name = 'path' }
  }, {
    { name = 'cmdline' }
  }),
  matching = { disallow_symbol_nonprefix_matching = false }
})


--
-- LSP (native vim.lsp.config for nvim 0.11+)
--

-- Configure LSP servers using the native API
vim.lsp.config('ruby_lsp', {})
vim.lsp.config('sorbet', {})
vim.lsp.config('ts_ls', {})

-- Enable all configured servers
vim.lsp.enable({ 'ruby_lsp', 'sorbet', 'ts_ls' })

-- Set up keymaps and options when an LSP attaches
vim.api.nvim_create_autocmd("LspAttach", {
  callback = function(args)
    local bufnr = args.buf
    local client = vim.lsp.get_client_by_id(args.data.client_id)

    -- Enable completion triggered by <c-x><c-o>
    vim.bo[bufnr].omnifunc = 'v:lua.vim.lsp.omnifunc'

    -- Keymaps
    local opts = { noremap = true, silent = true, buffer = bufnr }
    vim.keymap.set('n', 'gD', vim.lsp.buf.declaration, opts)
    vim.keymap.set('n', 'gd', vim.lsp.buf.definition, opts)
    vim.keymap.set('n', 'gr', vim.lsp.buf.references, opts)
    vim.keymap.set('n', '<leader><leader>', vim.lsp.buf.hover, opts)

    -- Disable ruby_lsp definition/semanticTokens (let sorbet handle these)
    if client and client.name == "ruby_lsp" then
      client.server_capabilities.definitionProvider = nil
      client.server_capabilities.semanticTokensProvider = nil
    end
  end,
})


--
-- lspfuzzy
--

require('lspfuzzy').setup {
  methods = 'all',         -- either 'all' or a list of LSP methods (see below)
  jump_one = true,         -- jump immediately if there is only one location
  callback = nil,          -- callback called after jumping to a location
  fzf_preview = {          -- arguments to the FZF '--preview-window' option
    'right:+{2}-/2'          -- preview on the right and centered on entry
  },
  fzf_action = {           -- FZF actions
    ['ctrl-t'] = 'tabedit',  -- go to location in a new tab
    ['ctrl-v'] = 'vsplit',   -- go to location in a vertical split
    ['ctrl-x'] = 'split',    -- go to location in a horizontal split
  },
  fzf_modifier = ':~:.',   -- format FZF entries, see |filename-modifiers|
  fzf_trim = true,         -- trim FZF entries
}

EOF

set timeoutlen=250
set ttimeoutlen=100
