# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Set name of the theme to load. Look in ~/.oh-my-zsh/themes/
ZSH_THEME="robbyrussell"
# HYPHEN_INSENSITIVE="true"
# ENABLE_CORRECTION="true"
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
plugins=(git)
source $ZSH/oh-my-zsh.sh

# Pure Prompt: https://github.com/sindresorhus/pure#getting-started
#autoload -U promptinit; promptinit
#prompt pure

# vim keybindings
set -o vi
bindkey "^R" history-incremental-search-backward

alias ccat='pygmentize -g -O style=colorful,linenos=1'
alias loadnvm="~/.nvm/nvm.sh"
alias lsc="clear && ls"
alias gb="git branch | cat"
alias safevim="vim -u NONE"
alias vimzsh="vim ~/.zshrc"
alias vimtmux="vim ~/.tmux.conf"
alias vimvim="vim ~/.vimrc"
alias nvimnvim="nvim ~/.vimrc"
alias reload="source ~/.zshrc"

alias vim="nvim"

export VISUAL=vim
export EDITOR="$VISUAL"

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
#export PATH="$PATH:$HOME/.rvm/bin"
#export PATH="/usr/local/opt/imagemagick@6/bin:$PATH"
#export PATH="$HOME/Library/Python/2.7/bin/:$PATH"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f /usr/share/doc/fzf/examples/key-bindings.zsh ] && source /usr/share/doc/fzf/examples/key-bindings.zsh


# CTRL-T file preview
export FZF_DEFAULT_COMMAND='ag -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_CTRL_T_OPTS="--preview '(bat --style=numbers --color=always {} || highlight -O ansi -l {} || coderay {} || rougify {} || cat {}) 2> /dev/null | head -500'"

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/mc mc
export GPG_TTY=`tty`

[ -f /opt/dev/dev.sh ] && source /opt/dev/dev.sh
if [ -e /Users/mitchvollebregt/.nix-profile/etc/profile.d/nix.sh ]; then . /Users/mitchvollebregt/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer

[[ -f /opt/dev/sh/chruby/chruby.sh ]] && type chruby >/dev/null 2>&1 || chruby () { source /opt/dev/sh/chruby/chruby.sh; chruby "$@"; }

[[ -x /usr/local/bin/brew ]] && eval $(/usr/local/bin/brew shellenv)
